"""Add is_admin column to User

Revision ID: 04eed4e6c636
Revises: c895dcec0638
Create Date: 2026-01-10 13:37:09.748101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04eed4e6c636'
down_revision = 'c895dcec0638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
